// Package types contains the generated Sophos types
//
// This file was generated by bin/gen.go! DO NOT EDIT!
package types

import (
	"fmt"

	"github.com/esurdam/go-sophos"
)

// SslVpn is a generated struct representing the Sophos SslVpn Endpoint
// GET /api/nodes/ssl_vpn
type SslVpn struct {
	AuthenticationAlgorithm string `json:"authentication_algorithm"`
	Certificate             string `json:"certificate"`
	Compression             int64  `json:"compression"`
	DatachannelKeyLifetime  int64  `json:"datachannel_key_lifetime"`
	Debug                   int64  `json:"debug"`
	DhKeySize               string `json:"dh_key_size"`
	DuplicateCn             int64  `json:"duplicate_cn"`
	EncryptionAlgorithm     string `json:"encryption_algorithm"`
	Hostname                string `json:"hostname"`
	Interface               string `json:"interface"`
	InterfaceAddress        string `json:"interface_address"`
	IPAssignmentPool        string `json:"ip_assignment_pool"`
	Port                    int64  `json:"port"`
	Protocol                string `json:"protocol"`
	UserAuthOptional        int64  `json:"user_auth_optional"`
}

var defsSslVpn = map[string]sophos.RestObject{
	"SslVpnClientConnection":    &SslVpnClientConnection{},
	"SslVpnGroup":               &SslVpnGroup{},
	"SslVpnRemoteAccessProfile": &SslVpnRemoteAccessProfile{},
	"SslVpnServerConnection":    &SslVpnServerConnection{},
}

// RestObjects implements the sophos.Node interface and returns a map of SslVpn's Objects
func (SslVpn) RestObjects() map[string]sophos.RestObject { return defsSslVpn }

// GetPath implements sophos.RestGetter
func (*SslVpn) GetPath() string { return "/api/nodes/ssl_vpn" }

// RefRequired implements sophos.RestGetter
func (*SslVpn) RefRequired() (string, bool) { return "", false }

var defSslVpn = &sophos.Definition{Description: "ssl_vpn", Name: "ssl_vpn", Link: "/api/definitions/ssl_vpn"}

// Definition returns the /api/definitions struct of SslVpn
func (SslVpn) Definition() sophos.Definition { return *defSslVpn }

// ApiRoutes returns all known SslVpn Paths
func (SslVpn) ApiRoutes() []string {
	return []string{
		"/api/objects/ssl_vpn/client_connection/",
		"/api/objects/ssl_vpn/client_connection/{ref}",
		"/api/objects/ssl_vpn/client_connection/{ref}/usedby",
		"/api/objects/ssl_vpn/group/",
		"/api/objects/ssl_vpn/group/{ref}",
		"/api/objects/ssl_vpn/group/{ref}/usedby",
		"/api/objects/ssl_vpn/remote_access_profile/",
		"/api/objects/ssl_vpn/remote_access_profile/{ref}",
		"/api/objects/ssl_vpn/remote_access_profile/{ref}/usedby",
		"/api/objects/ssl_vpn/server_connection/",
		"/api/objects/ssl_vpn/server_connection/{ref}",
		"/api/objects/ssl_vpn/server_connection/{ref}/usedby",
	}
}

// References returns the SslVpn's references. These strings serve no purpose other than to demonstrate which
// Reference keys are used for this Endpoint
func (SslVpn) References() []string {
	return []string{
		"REF_SslVpnClientConnection",
		"REF_SslVpnGroup",
		"REF_SslVpnRemoteAccessProfile",
		"REF_SslVpnServerConnection",
	}
}

// SslVpnClientConnections is an Sophos Endpoint subType and implements sophos.RestObject
type SslVpnClientConnections []SslVpnClientConnection

// SslVpnClientConnection is a generated Sophos object
type SslVpnClientConnection struct {
	Locked                  string   `json:"_locked"`
	Reference               string   `json:"_ref"`
	_type                   string   `json:"_type"`
	AuthenticationAlgorithm string   `json:"authentication_algorithm"`
	AutoPfIn                string   `json:"auto_pf_in"`
	AutoPfOut               string   `json:"auto_pf_out"`
	AutoPfrule              bool     `json:"auto_pfrule"`
	CaCert                  string   `json:"ca_cert"`
	Certificate             string   `json:"certificate"`
	Comment                 string   `json:"comment"`
	Compression             bool     `json:"compression"`
	EncryptionAlgorithm     string   `json:"encryption_algorithm"`
	Engine                  string   `json:"engine"`
	Interface               string   `json:"interface"`
	Key                     string   `json:"key"`
	LocalNetworks           []string `json:"local_networks"`
	Name                    string   `json:"name"`
	Password                string   `json:"password"`
	PlainServerAddress      string   `json:"plain_server_address"`
	Protocol                string   `json:"protocol"`
	ProxyAuthPass           string   `json:"proxy_auth_pass"`
	ProxyAuthStatus         bool     `json:"proxy_auth_status"`
	ProxyAuthUser           string   `json:"proxy_auth_user"`
	ProxyHost               string   `json:"proxy_host"`
	ProxyPort               int64    `json:"proxy_port"`
	ProxyStatus             bool     `json:"proxy_status"`
	RemoteNetworks          []string `json:"remote_networks"`
	ServerAddress           string   `json:"server_address"`
	ServerDn                string   `json:"server_dn"`
	ServerOverrideHostname  string   `json:"server_override_hostname"`
	ServerOverrideStatus    bool     `json:"server_override_status"`
	ServerPort              int64    `json:"server_port"`
	Status                  bool     `json:"status"`
	Username                string   `json:"username"`
}

// GetPath implements sophos.RestObject and returns the SslVpnClientConnections GET path
// Returns all available ssl_vpn/client_connection objects
func (*SslVpnClientConnections) GetPath() string { return "/api/objects/ssl_vpn/client_connection/" }

// RefRequired implements sophos.RestObject
func (*SslVpnClientConnections) RefRequired() (string, bool) { return "", false }

// GetPath implements sophos.RestObject and returns the SslVpnClientConnections GET path
// Returns all available client_connection types
func (s *SslVpnClientConnection) GetPath() string {
	return fmt.Sprintf("/api/objects/ssl_vpn/client_connection/%s", s.Reference)
}

// RefRequired implements sophos.RestObject
func (s *SslVpnClientConnection) RefRequired() (string, bool) { return s.Reference, true }

// DeletePath implements sophos.RestObject and returns the SslVpnClientConnection DELETE path
// Creates or updates the complete object client_connection
func (*SslVpnClientConnection) DeletePath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/client_connection/%s", ref)
}

// PatchPath implements sophos.RestObject and returns the SslVpnClientConnection PATCH path
// Changes to parts of the object client_connection types
func (*SslVpnClientConnection) PatchPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/client_connection/%s", ref)
}

// PostPath implements sophos.RestObject and returns the SslVpnClientConnection POST path
// Create a new ssl_vpn/client_connection object
func (*SslVpnClientConnection) PostPath() string {
	return "/api/objects/ssl_vpn/client_connection/"
}

// PutPath implements sophos.RestObject and returns the SslVpnClientConnection PUT path
// Creates or updates the complete object client_connection
func (*SslVpnClientConnection) PutPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/client_connection/%s", ref)
}

// GetType implements sophos.Object
func (s *SslVpnClientConnection) GetType() string { return s._type }

// SslVpnGroup is an Sophos Endpoint subType and implements sophos.RestObject
type SslVpnGroup []interface{}

// GetPath implements sophos.RestObject and returns the SslVpnGroup GET path
// Returns all available ssl_vpn/group objects
func (*SslVpnGroup) GetPath() string { return "/api/objects/ssl_vpn/group/" }

// RefRequired implements sophos.RestObject
func (*SslVpnGroup) RefRequired() (string, bool) { return "", false }

// DeletePath implements sophos.RestObject and returns the SslVpnGroup DELETE path
// Creates or updates the complete object group
func (*SslVpnGroup) DeletePath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/group/%s", ref)
}

// PatchPath implements sophos.RestObject and returns the SslVpnGroup PATCH path
// Changes to parts of the object group types
func (*SslVpnGroup) PatchPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/group/%s", ref)
}

// PostPath implements sophos.RestObject and returns the SslVpnGroup POST path
// Create a new ssl_vpn/group object
func (*SslVpnGroup) PostPath() string {
	return "/api/objects/ssl_vpn/group/"
}

// PutPath implements sophos.RestObject and returns the SslVpnGroup PUT path
// Creates or updates the complete object group
func (*SslVpnGroup) PutPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/group/%s", ref)
}

// SslVpnRemoteAccessProfiles is an Sophos Endpoint subType and implements sophos.RestObject
type SslVpnRemoteAccessProfiles []SslVpnRemoteAccessProfile

// SslVpnRemoteAccessProfile is a generated Sophos object
type SslVpnRemoteAccessProfile struct {
	Locked     string   `json:"_locked"`
	Reference  string   `json:"_ref"`
	_type      string   `json:"_type"`
	Aaa        []string `json:"aaa"`
	AutoPfIn   string   `json:"auto_pf_in"`
	AutoPfrule bool     `json:"auto_pfrule"`
	Comment    string   `json:"comment"`
	Name       string   `json:"name"`
	Networks   []string `json:"networks"`
	Status     bool     `json:"status"`
}

// GetPath implements sophos.RestObject and returns the SslVpnRemoteAccessProfiles GET path
// Returns all available ssl_vpn/remote_access_profile objects
func (*SslVpnRemoteAccessProfiles) GetPath() string {
	return "/api/objects/ssl_vpn/remote_access_profile/"
}

// RefRequired implements sophos.RestObject
func (*SslVpnRemoteAccessProfiles) RefRequired() (string, bool) { return "", false }

// GetPath implements sophos.RestObject and returns the SslVpnRemoteAccessProfiles GET path
// Returns all available remote_access_profile types
func (s *SslVpnRemoteAccessProfile) GetPath() string {
	return fmt.Sprintf("/api/objects/ssl_vpn/remote_access_profile/%s", s.Reference)
}

// RefRequired implements sophos.RestObject
func (s *SslVpnRemoteAccessProfile) RefRequired() (string, bool) { return s.Reference, true }

// DeletePath implements sophos.RestObject and returns the SslVpnRemoteAccessProfile DELETE path
// Creates or updates the complete object remote_access_profile
func (*SslVpnRemoteAccessProfile) DeletePath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/remote_access_profile/%s", ref)
}

// PatchPath implements sophos.RestObject and returns the SslVpnRemoteAccessProfile PATCH path
// Changes to parts of the object remote_access_profile types
func (*SslVpnRemoteAccessProfile) PatchPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/remote_access_profile/%s", ref)
}

// PostPath implements sophos.RestObject and returns the SslVpnRemoteAccessProfile POST path
// Create a new ssl_vpn/remote_access_profile object
func (*SslVpnRemoteAccessProfile) PostPath() string {
	return "/api/objects/ssl_vpn/remote_access_profile/"
}

// PutPath implements sophos.RestObject and returns the SslVpnRemoteAccessProfile PUT path
// Creates or updates the complete object remote_access_profile
func (*SslVpnRemoteAccessProfile) PutPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/remote_access_profile/%s", ref)
}

// GetType implements sophos.Object
func (s *SslVpnRemoteAccessProfile) GetType() string { return s._type }

// SslVpnServerConnection is an Sophos Endpoint subType and implements sophos.RestObject
type SslVpnServerConnection []interface{}

// GetPath implements sophos.RestObject and returns the SslVpnServerConnection GET path
// Returns all available ssl_vpn/server_connection objects
func (*SslVpnServerConnection) GetPath() string { return "/api/objects/ssl_vpn/server_connection/" }

// RefRequired implements sophos.RestObject
func (*SslVpnServerConnection) RefRequired() (string, bool) { return "", false }

// DeletePath implements sophos.RestObject and returns the SslVpnServerConnection DELETE path
// Creates or updates the complete object server_connection
func (*SslVpnServerConnection) DeletePath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/server_connection/%s", ref)
}

// PatchPath implements sophos.RestObject and returns the SslVpnServerConnection PATCH path
// Changes to parts of the object server_connection types
func (*SslVpnServerConnection) PatchPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/server_connection/%s", ref)
}

// PostPath implements sophos.RestObject and returns the SslVpnServerConnection POST path
// Create a new ssl_vpn/server_connection object
func (*SslVpnServerConnection) PostPath() string {
	return "/api/objects/ssl_vpn/server_connection/"
}

// PutPath implements sophos.RestObject and returns the SslVpnServerConnection PUT path
// Creates or updates the complete object server_connection
func (*SslVpnServerConnection) PutPath(ref string) string {
	return fmt.Sprintf("/api/objects/ssl_vpn/server_connection/%s", ref)
}
