name: Github CI

on:
  push:
    branches:
      - feature/*
      - master
  pull_request:
    branches: [ testing, master ]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2
      - name: test
        run: make test && bash <(curl -s https://codecov.io/bash)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}